apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
- deployment.yaml
- namespace.yaml
- origin-cert.yaml
- podmonitor.yaml
- tunnel-credentials.yaml
configMapGenerator:
- name: cloudflared-config
  files:
  - config.yml
