apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/garage/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
