apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pyroscope
  namespace: flux-system
spec:
  interval: 24h
  path: "./clusters/home.axe.al/infrastructure/pyroscope"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: pyroscope
      namespace: pyroscope
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: alloy
      namespace: pyroscope
  timeout: 5m
